{% set version = '1.14' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-missmda
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/missMDA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/missMDA/missMDA_{{ version }}.tar.gz
  sha256: 90166e0f5e848197001d83452456e1f29a17278988c8d66824c2c47383761cdf

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-factominer
    - r-doparallel
    - r-foreach
    - r-mice
    - r-mvtnorm
  run:
    - r-base
    - r-factominer
    - r-doparallel
    - r-foreach
    - r-mice
    - r-mvtnorm

test:
  commands:
    - $R -e "library('missMDA')"           # [not win]
    - "\"%R%\" -e \"library('missMDA')\""  # [win]

about:
  home: https://husson.github.io/, http://juliejosse.com/
  license: GPL (>= 2)
  summary: Imputation of incomplete continuous or categorical datasets; Missing values are imputed
    with a principal component analysis (PCA), a multiple correspondence analysis (MCA)
    model or a multiple factor analysis (MFA) model; Perform multiple imputation with
    and in PCA or MCA.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - rasmusagren

# Package: missMDA
# Type: Package
# Title: Handling Missing Values with Multivariate Data Analysis
# Version: 1.14
# Date: 2019-01-23
# Author: Francois Husson, Julie Josse
# Maintainer: Francois Husson <husson@agrocampus-ouest.fr>
# Description: Imputation of incomplete continuous or categorical datasets; Missing values are imputed with a principal component analysis (PCA), a multiple correspondence analysis (MCA) model or a multiple factor analysis (MFA) model; Perform multiple imputation with and in PCA or MCA.
# Depends: R (>= 3.3.0)
# Imports: FactoMineR,graphics,grDevices,mice,mvtnorm,stats,utils,doParallel,parallel,foreach
# Suggests: knitr
# License: GPL (>= 2)
# URL: https://husson.github.io/, http://juliejosse.com/
# Encoding: latin1
# LazyLoad: yes
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-01-23 10:12:15 UTC; husson
# Repository: CRAN
# Date/Publication: 2019-01-23 10:50:03 UTC
