appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: l6Ca4/v8Xj5XMZTU2SQtDRB73GLgaL7MeODv7Vi3R42Z3MbhVbYsiQiWCRRjvp82UvvGG4w2aSWhD58M1yFwNqLh4pvlCGZ2PRSByhofR+nwUIweJDBiGIMmlmJtEBiBXs7xonIfnE86Sdv174WYd4ujTyeJbqGwvwKZOq/m1sDrAb08KFWSdz2inpi5cuRRMOXL91aDhOONxgfkIgXfq8+5KEidCgUD/LZXw7jjWlJRYjnQ0YtD+2P19ubeIKaZZ5pB4SOWStfb8OoIYgUuOfQVnZh0E4LNLWo1x/WzZy5Uj9DjastrD2uILXxS7reAY8ZAF9Rxts3KvUdV7VOAHkV2QJQh/VeC6vSawEoRGp61irg82RjV0JSvrryVxPP19JAhubZbaaW9Mh8TyQnOuZm8RKdemcygK7jNC9OOy8emh2sZUJlMW/cRnX3Yoa5WZCOE+P/ySK2s61FgidlFye+3aRcASB55C0Zipw42WZcaAEez865ulb8WomeiQU90Bh+TnmqTgloLoXh8P19MrjsCSwtljezgnEte3Kq3b+elJ6AaT6QFwkHEFpbQXhtRWOc1o1Sxr2DuNZsChX/krjNxCTTjbr879k2xhR0a8egIzdrPfwGYu0MCsMJzZTPjOWEVE96erCeHU+nB2l4usOcZ+RkkJtSyVJ4tCxhRA/0=
conda_forge_output_validation: true
